"""Compile manually reviewed facts; does not scrape restricted websites."""
import json
from pathlib import Path

entities, sources, claims = [], [], []
def entity(id, kind, name, description, **extra):
    entities.append(dict(id=id, kind=kind, name=name, description=description, **extra))

for id, name in [("electronics", "Consumer electronics"), ("semiconductors", "Semiconductors")]:
    entity(id, "industry", name, "Collection taxonomy; classification does not establish a supply relationship.")
for id, name in [("processors", "Application processors"), ("io", "I/O controllers"), ("power", "Power management"), ("wireless", "Wireless connectivity"), ("ethernet", "Ethernet"), ("assembly", "Board assembly"), ("microcontrollers", "Microcontrollers")]:
    entity(id, "category", name, "Component category, distinct from a specific part.", industry_id="semiconductors" if id != "assembly" else "electronics")
entity("wales", "region", "Wales, United Kingdom", "Geographic region. Only documented facility relationships establish exposure.")
entity("silicon", "material", "Silicon", "Upstream material coverage is not yet established. No refinery, wafer or material supplier is claimed.", industry_id="semiconductors")
for id, name, aliases in [("raspberry-pi", "Raspberry Pi", ["Raspberry Pi Ltd", "Raspberry Pi Trading"]), ("broadcom", "Broadcom", ["Broadcom Inc."]), ("renesas", "Renesas", ["Renesas Electronics"]), ("infineon", "Infineon", ["Infineon Technologies"]), ("tsmc", "TSMC", ["Taiwan Semiconductor Manufacturing Company"]), ("sony", "Sony", ["Sony UK TEC"]), ("via", "VIA Labs", ["VLI"])]:
    entity(id, "company", name, "See individual claims for documented roles, products, periods and manufacturing locations.", aliases=aliases, industry_id="electronics" if id in ("raspberry-pi", "sony") else "semiconductors")
entity("pencoed", "facility", "Sony UK Technology Centre", "Pencoed, South Wales. Documented board assembly; this is not evidence of semiconductor fabrication here.", region_id="wales", latitude=51.523, longitude=-3.5, precision="approximate", location_reference="Town-level placement for Pencoed, South Wales, identified in the Pi 5 launch article; not a surveyed factory coordinate.", industry_id="electronics")
for id, name, desc in [("pi5", "Raspberry Pi 5", "Flagship single-board computer · 2023 launch collection"), ("pi4", "Raspberry Pi 4 Model B", "Single-board computer · partial chipset collection"), ("pi500", "Raspberry Pi 500", "Keyboard computer · shared BCM2712 and RP1 dependencies"), ("pi400", "Raspberry Pi 400", "Keyboard computer · shared BCM2711 dependency"), ("pico", "Raspberry Pi Pico", "Microcontroller board · RP2040 and upstream fabrication")]:
    entity(id, "product", name, desc + ". A documented partial breakdown, not a complete bill of materials.", industry_id="electronics", aliases=[name.replace("Raspberry Pi", "Pi")])
for ram in (4, 8):
    entity(f"pi5-{ram}gb", "variant", f"Raspberry Pi 5 · {ram} GB", "Launch memory variant. Claims without variant scope do not establish variant-specific sourcing.", parent_id="pi5", industry_id="electronics")
for id, name, category, desc in [("bcm2712", "BCM2712", "processors", "Broadcom application processor"), ("bcm2711", "BCM2711", "processors", "Broadcom application processor"), ("rp1", "RP1", "io", "Raspberry Pi I/O controller"), ("da9091", "DA9091", "power", "Renesas power-management IC"), ("cyw43455", "CYW43455", "wireless", "Infineon Wi-Fi and Bluetooth device"), ("bcm54213", "BCM54213", "ethernet", "Broadcom Gigabit Ethernet PHY"), ("vl805", "VL805", "io", "VIA Labs USB controller"), ("rp2040", "RP2040", "microcontrollers", "Raspberry Pi microcontroller"), ("pi5-board", "Pi 5 board assembly", "assembly", "Product-specific assembled board; not an upstream chip fabrication stage")]:
    entity(id, "part", name, desc + ". Inspect claims for evidence and sourcing scope.", category_id=category, industry_id="electronics" if category == "assembly" else "semiconductors")

def source(id, title, url, published=None, licensed=False):
    sources.append(dict(id=id,title=title,url=url,publisher="Raspberry Pi Ltd",published=published,retrieved="2026-09-10",license="CC BY-SA 4.0" if licensed else "Publicly viewable; all rights reserved",terms_url="https://www.raspberrypi.com/licensing/" if licensed else "https://www.raspberrypi.com/terms-and-conditions/",reuse="Adapted factual identification with attribution. Documentation-derived data is CC BY-SA 4.0; changes: normalized into entity and claim records." if licensed else "Manual factual reference only. No article text, images or full-page copy redistributed. Automated scraping disabled under source terms.",adapter="raspberrypi-docs" if licensed else "manual-reference"))
source("pi5-launch", "Introducing: Raspberry Pi 5!", "https://www.raspberrypi.com/news/introducing-raspberry-pi-5/", "2023-09-28")
source("rp1-design", "RP1: the silicon controlling Raspberry Pi 5 I/O", "https://www.raspberrypi.com/news/rp1-the-silicon-controlling-raspberry-pi-5-i-o-designed-here-at-raspberry-pi/", "2023-10-06")
source("bcm2711-doc", "BCM2711 processor documentation", "https://github.com/raspberrypi/documentation/blob/master/documentation/asciidoc/computers/processors/bcm2711.adoc", licensed=True)
source("keyboard-doc", "Keyboard computer processor documentation", "https://github.com/raspberrypi/documentation/blob/master/documentation/asciidoc/computers/keyboard-computers/intro.adoc", licensed=True)
source("pi500-spec", "Raspberry Pi 500 product specifications", "https://www.raspberrypi.com/products/raspberry-pi-500/")
source("pico-launch", "Meet Raspberry Silicon: Raspberry Pi Pico", "https://www.raspberrypi.com/news/raspberry-pi-silicon-pico-now-on-sale/", "2021-01-21")
source("rp2040-process", "Raspberry Pi Direct: RP2040", "https://www.raspberrypi.com/news/raspberry-pi-direct-buy-rp2040-in-bulk-from-just-0-70/", "2022-01-17")

def claim(id, supplier, part, product, role, source_id, reference, observed, **extra):
    record=dict(id=id,supplier_id=supplier,customer_id="raspberry-pi",part_id=part,product_id=product,role=role,status="direct",observed_at=observed,period="Documented at source date; end date and present-day continuity unconfirmed.",uncertainty="Specific manufacturing facility, batch allocation and alternate suppliers are not established. This record does not establish sole sourcing.",evidence=[dict(source_id=source_id,reference=reference)])
    record.update(extra)
    claims.append(record)
for part, supplier, role, ref in [("bcm2712","broadcom","designer","New platform, new chipset / BCM2712"),("rp1","raspberry-pi","designer","New platform, new chipset / RP1"),("da9091","renesas","component supplier","New platform, new chipset / DA9091"),("cyw43455","infineon","component supplier","Paragraph following DA9091: retained wireless chipset"),("bcm54213","broadcom","component supplier","Paragraph following DA9091: Ethernet PHY")]:
    claim("pi5-"+part,supplier,part,"pi5",role,"pi5-launch",ref,"2023-09-28")
claim("pi5-assembly","sony","pi5-board","pi5","assembler","pi5-launch","Designed in Cambridge, manufactured in Wales","2023-09-28",facility_id="pencoed",region_id="wales",uncertainty="Board assembly in Pencoed is supported for the 2023 launch. Chip fabrication at this facility, all later batches and exclusivity are not established.")
claim("rp1-fabrication","tsmc","rp1",None,"fabricator","rp1-design","Opening technical description: TSMC 40LP implementation","2023-10-06",uncertainty="TSMC process is identified for RP1. Specific fab and country of fabrication are undisclosed. Applying this part-level sourcing to later products is an inference, not a product-specific sourcing confirmation.")
for part,supplier,ref in [("cyw43455","infineon","New platform, new chipset: wireless device retained from Pi 4"),("bcm54213","broadcom","New platform, new chipset: Ethernet PHY retained"),("vl805","via","RP1 section: Pi 4 external USB controller")]:
    claim("pi4-"+part,supplier,part,"pi4","component supplier","pi5-launch",ref,"2023-09-28")
for product in ("pi4","pi400"):
    claim(product+"-bcm2711","broadcom","bcm2711",product,"designer","bcm2711-doc","Opening paragraph: BCM2711 product list","2026-09-10",period="Documentation retrieved September 2026; publication and batch dates not supplied.")
for part,supplier in [("bcm2712","broadcom"),("rp1","raspberry-pi")]:
    claim("pi500-"+part,supplier,part,"pi500","designer","keyboard-doc","Introduction: processor and I/O controller identification","2026-09-10",period="Documentation retrieved September 2026; production allocation not supplied.")
claim("pico-rp2040","raspberry-pi","rp2040","pico","designer","pico-launch","Opening product announcement and RP2040 description","2021-01-21")
claim("rp2040-fabrication","tsmc","rp2040",None,"fabricator","rp2040-process","TSMC 40LP process discussion","2022-01-17",uncertainty="Part-level fabrication process evidence. Fab location, packaging provider and product/batch allocation remain unknown.")

# Second reviewed collection: historical, product-scoped factory examples and
# additional shared microcontroller dependencies. Restricted prose is not copied.
for id, name in [("graphics", "Graphics processors"), ("security", "Security controllers"), ("accelerators", "Video accelerators"), ("memory", "Memory and storage"), ("timing", "Timing devices"), ("sensors", "Image sensors"), ("enclosures", "Mechanical enclosures")]:
    entity(id, "category", name, "Component category, distinct from a specific part.", industry_id="electronics" if id == "enclosures" else "semiconductors")
for id, name in [("texas", "Texas, United States"), ("uttar-pradesh", "Uttar Pradesh, India")]:
    entity(id, "region", name, "Manufacturing exposure requires an individually evidenced facility or geography claim; headquarters do not establish exposure.")
entity("aluminium", "material", "Aluminium", "The Mac Pro 2019 housing is documented as aluminium. Smelter, refiner, alloy, origin and material supplier remain unknown.", aliases=["Aluminum"], industry_id="electronics")
for id, name, aliases in [("apple", "Apple", ["Apple Inc."]), ("intel", "Intel", ["Intel Corporation"]), ("amd", "AMD", ["Advanced Micro Devices"]), ("samsung", "Samsung Electronics", ["Samsung", "Samsung India Electronics"]), ("qualcomm", "Qualcomm", ["Qualcomm Technologies"]), ("winbond", "Winbond", ["Winbond Electronics"]), ("abracon", "Abracon", [])]:
    entity(id, "company", name, "Supplier identity is tied to individual source-backed parts and roles. Other factories and commercial relationships are not implied.", aliases=aliases, industry_id="electronics" if id in ("apple", "samsung") else "semiconductors")
entity("mac-pro-austin", "facility", "Mac Pro assembly facility, Austin", "Apple's November 2019 disclosure identifies final assembly of Mac Pro units shipping to the Americas at this Austin site. The cited source does not name the contract operator or street address; this is not Apple's office campus or a semiconductor fab.", region_id="texas", latitude=30.267, longitude=-97.743, precision="approximate", location_reference="Austin city-level marker only, based on Apple, 'Apple expands in Austin', November 20, 2019. Exact factory coordinates are not established by the source.", industry_id="electronics")
entity("samsung-noida", "facility", "Samsung Noida mobile factory", "Samsung's July 2018 plant announcement explicitly includes Galaxy S9 assembly for the Indian market. It does not locate the manufacture of the phone's chips here.", parent_id="samsung", region_id="uttar-pradesh", latitude=28.535, longitude=77.391, precision="approximate", location_reference="Noida city-level marker only. Samsung's July 9, 2018 announcement identifies Noida, Uttar Pradesh; no surveyed plant boundary or exact coordinate is asserted.", industry_id="electronics")
for id, name, desc, aliases in [
    ("mac-pro-2019", "Apple Mac Pro (2019)", "Modular Intel workstation with configurable graphics and a documented Austin final-assembly relationship for the Americas", ["Mac Pro 2019", "2019 Mac Pro"]),
    ("galaxy-s9", "Samsung Galaxy S9", "2018 smartphone with region-dependent processors and documented Noida assembly for India", ["Galaxy S9", "S9"]),
    ("pico2", "Raspberry Pi Pico 2", "RP2350 microcontroller board with identified flash, timing device and upstream process evidence", ["Pico 2", "Pi Pico 2"]),
    ("pico-w", "Raspberry Pi Pico W", "Wireless RP2040 board sharing microcontroller sourcing with Pico", ["Pico W", "Pi Pico W"]),
]:
    entity(id, "product", name, desc + ". Historical documented partial breakdown; not a complete bill of materials or present-day sourcing guarantee.", aliases=aliases, industry_id="electronics")
for id, name, parent, desc in [
    ("mac-pro-2019-8core", "Mac Pro 2019 · 8-core configuration", "mac-pro-2019", "3.5 GHz eight-core Intel Xeon W configuration documented by Apple; graphics and storage remain configurable."),
    ("galaxy-s9-exynos", "Galaxy S9 · Exynos configuration", "galaxy-s9", "Configuration containing Exynos 9810. The reviewed component source warns that components differ by country and carrier; no exhaustive market list is inferred."),
    ("galaxy-s9-snapdragon", "Galaxy S9 · Snapdragon configuration", "galaxy-s9", "Configuration containing Snapdragon 845 in the select regions described by Qualcomm. This record does not assign it to Noida manufacturing batches."),
]:
    entity(id, "variant", name, desc, parent_id=parent, industry_id="electronics")
for id, name, category, desc in [
    ("xeon-w-8core-2019", "Intel Xeon W · 8-core / 3.5 GHz", "processors", "The specific eight-core processor configuration listed for Mac Pro 2019. Apple's cited specification does not disclose an Intel order code; one is not inferred."),
    ("radeon-pro-580x", "Radeon Pro 580X", "graphics", "AMD graphics option documented for the configurable Mac Pro 2019; not installed in every unit."),
    ("apple-t2", "Apple T2 Security Chip", "security", "Apple security controller identified in the Mac Pro 2019 storage specification."),
    ("apple-afterburner", "Apple Afterburner", "accelerators", "Optional video accelerator card offered for Mac Pro 2019. The chip fabricator and card assembler are undisclosed."),
    ("mac-pro-2019-housing", "Mac Pro 2019 aluminium housing", "enclosures", "Product-specific removable housing. Its material identity is documented, while the material supplier and housing factory are unknown."),
    ("mac-pro-2019-assembly", "Mac Pro 2019 final assembly", "assembly", "Product-level assembly stage for the 2019 Mac Pro; not fabrication of its Intel, AMD or Apple chips."),
    ("exynos-9810", "Exynos 9810", "processors", "Samsung processor used in some Galaxy S9 configurations, with country and carrier qualifications."),
    ("snapdragon-845", "Snapdragon 845", "processors", "Qualcomm mobile platform used in Galaxy S9 in select regions."),
    ("isocell-2l3", "ISOCELL Fast 2L3", "sensors", "Samsung main camera sensor identified for Galaxy S9; supplier configuration can differ by country and carrier."),
    ("isocell-3h1", "ISOCELL Bright 3H1", "sensors", "Samsung front camera sensor identified for Galaxy S9; supplier configuration can differ by country and carrier."),
    ("galaxy-s9-assembly", "Galaxy S9 final assembly", "assembly", "Product-specific phone assembly; location is not inherited by semiconductor claims."),
    ("rp2350", "RP2350", "microcontrollers", "Raspberry Pi microcontroller used by Pico 2 (RP2350A package); part-level TSMC process evidence does not identify a fab or batch."),
    ("cyw43439", "CYW43439", "wireless", "Infineon wireless device identified for Raspberry Pi Pico W."),
    ("w25q32rv", "W25Q32RV", "memory", "Winbond flash device named in the Pico 2 datasheet revision reviewed in July 2026."),
    ("abm8-272-t3", "ABM8-272-T3", "timing", "Abracon crystal identified in the Pico 2 external circuitry description."),
]:
    entity(id, "part", name, desc, category_id=category, industry_id="electronics" if category in ("assembly", "enclosures") else "semiconductors")

def manual_source(id, title, url, publisher, terms_url, published=None, reuse=None):
    sources.append(dict(id=id, title=title, url=url, publisher=publisher, published=published, retrieved="2026-09-10", license="Publicly viewable; not open-licensed", terms_url=terms_url, reuse=reuse or "Manual factual identification and precise citation only. No source prose, images, tables or page copies are redistributed. No automated collection or content-reuse permission is assumed.", adapter="manual-reference"))

manual_source("mac-pro-2019-spec", "Mac Pro (2019) technical specifications", "https://support.apple.com/en-us/118461", "Apple Inc.", "https://www.apple.com/legal/internet-services/terms/site.html")
manual_source("mac-pro-2019-launch", "Apple unveils all-new Mac Pro and Pro Display XDR", "https://www.apple.com/newsroom/2019/06/apple-unveils-powerful-all-new-mac-pro-and-groundbreaking-pro-display-xdr/", "Apple Inc.", "https://www.apple.com/legal/internet-services/terms/site.html", "2019-06-03")
manual_source("mac-pro-austin-production", "Apple expands in Austin", "https://www.apple.com/newsroom/2019/11/apple-expands-in-austin/", "Apple Inc.", "https://www.apple.com/legal/internet-services/terms/site.html", "2019-11-20")
manual_source("samsung-noida-production", "Samsung inaugurates expanded Noida mobile factory", "https://news.samsung.com/in/samsung-inaugurates-worlds-largest-mobile-factory-in-india", "Samsung Electronics", "https://news.samsung.com/in/terms", "2018-07-09")
manual_source("galaxy-s9-components", "Invisible Details Make the Galaxy S9 More Powerful", "https://semiconductor.samsung.com/news-events/tech-blog/invisible-details-make-the-galaxy-s9-more-powerful/", "Samsung Electronics", "https://semiconductor.samsung.com/legal/")
manual_source("galaxy-s9-snapdragon", "Snapdragon 845 powers Samsung Galaxy S9 and S9+ in select regions", "https://www.qualcomm.com/news/releases/2018/02/qualcomm-snapdragon-845-mobile-platform-powers-advanced-connectivity-and", "Qualcomm Technologies, Inc.", "https://www.qualcomm.com/site/terms-of-use", "2018-02-24")
source("pico-w-launch", "Raspberry Pi Pico W: your IoT platform", "https://www.raspberrypi.com/news/raspberry-pi-pico-w-your-6-iot-platform/", "2022-06-30")
source("pico2-launch", "Raspberry Pi Pico 2 launch", "https://www.raspberrypi.com/news/raspberry-pi-pico-2-our-new-5-microcontroller-board-on-sale-now/", "2024-08-08")
source("rp2350-process", "RP2350: the brains of Raspberry Pi Pico 2", "https://www.raspberrypi.com/news/rp2350-the-brains-of-raspberry-pi-pico-2/", "2024-09-11")
manual_source("pico2-datasheet", "Raspberry Pi Pico 2 Datasheet (July 2026 revision)", "https://datasheets.raspberrypi.com/pico/pico-2-datasheet.pdf", "Raspberry Pi Ltd", "https://datasheets.raspberrypi.com/pico/pico-2-datasheet.pdf", "2026-07-03", reuse="Manual component identification only, with precise page references. PDF colophon restricts resource use; section 1.1 separately permits reuse of hardware design files. Neither permission is presented as an open licence for the full PDF. No PDF prose, images or tables are bundled.")

claim("mac-pro-2019-cpu", "intel", "xeon-w-8core-2019", "mac-pro-2019", "designer", "mac-pro-2019-spec", "Processor / 8-Core: Intel Xeon W, 3.5 GHz", "2026-09-10", customer_id="apple", variant_id="mac-pro-2019-8core", period="2019 model specification retrieved September 2026; individual production dates are unspecified.", uncertainty="Eight-core configuration only. Exact Intel ordering code, chip fabrication site, assembly batch and alternate configurations are not established by this record.")
claim("mac-pro-2019-gpu", "amd", "radeon-pro-580x", "mac-pro-2019", "designer", "mac-pro-2019-spec", "Graphics / AMD Radeon Pro 580X option", "2026-09-10", customer_id="apple", period="Historical 2019-model configuration option; documentation retrieved September 2026.", uncertainty="An offered graphics option, not a part installed in every Mac Pro. GPU wafer fab, MPX module assembler and production allocation remain unknown.")
claim("mac-pro-2019-t2", "apple", "apple-t2", "mac-pro-2019", "designer", "mac-pro-2019-spec", "Storage / encryption by Apple T2 Security Chip", "2026-09-10", customer_id="apple", period="Historical 2019-model specification retrieved September 2026.")
claim("mac-pro-2019-afterburner", "apple", "apple-afterburner", "mac-pro-2019", "designer", "mac-pro-2019-launch", "Introducing Apple Afterburner section; configurable video accelerator", "2019-06-03", customer_id="apple", uncertainty="Optional accelerator for configured units; not a standard component in all Mac Pro computers. Semiconductor fabricator, card assembler and facility remain unknown.")
claim("mac-pro-2019-material", None, "mac-pro-2019-housing", "mac-pro-2019", "material supplier", "mac-pro-2019-launch", "Stunning Modular Enclosure with 360-Degree Access / aluminium housing", "2019-06-03", customer_id="apple", material_id="aluminium", uncertainty="Only the housing's aluminium material is documented. The material supplier, alloy, mine, smelter, refinery and housing fabrication site are unknown. Austin final assembly does not establish where this housing was made.")
claim("mac-pro-2019-final-assembly", None, "mac-pro-2019-assembly", "mac-pro-2019", "assembler", "mac-pro-austin-production", "Opening production paragraphs and Making Mac Pro in the US / Austin assembly and shipments to the Americas", "2019-11-20", customer_id="apple", facility_id="mac-pro-austin", region_id="texas", uncertainty="2019 final assembly for units shipping to the Americas is documented. The article leaves the contract operator unnamed. Other markets, later generations, component manufacture and exclusive sourcing are not established.")
claim("galaxy-s9-final-assembly", "samsung", "galaxy-s9-assembly", "galaxy-s9", "assembler", "samsung-noida-production", "Paragraph beginning As a true market leader / Galaxy S9, S9+ and Note8 explicitly named at Noida", "2018-07-09", customer_id="samsung", facility_id="samsung-noida", region_id="uttar-pradesh", uncertainty="Phone assembly for the Indian market is documented in July 2018. Individual chipset variants, batch allocation, other markets and present-day production are not established. No chip fabrication at Noida is implied.")
claim("galaxy-s9-exynos", "samsung", "exynos-9810", "galaxy-s9", "designer", "galaxy-s9-components", "Powerful mobile computing / Exynos 9 Series 9810; country-and-carrier qualification at end", "2026-09-10", customer_id="samsung", variant_id="galaxy-s9-exynos", period="Historical Galaxy S9 configuration; source publication date unavailable, retrieved September 2026.", uncertainty="Documented Exynos configuration only. Samsung explicitly qualifies the component list by country and carrier. This does not establish a region list, a particular Noida batch or a wafer fab.")
claim("galaxy-s9-snapdragon", "qualcomm", "snapdragon-845", "galaxy-s9", "designer", "galaxy-s9-snapdragon", "Opening paragraph / Galaxy S9 and S9+ in select regions", "2018-02-24", customer_id="samsung", variant_id="galaxy-s9-snapdragon", uncertainty="Qualcomm specifies select regions without enumerating them in this source. No assignment to India or the Noida plant, exclusive sourcing, wafer fab or packaging facility is inferred.")
for part, ref in [("isocell-2l3", "Component diagram / Main Camera: ISOCELL Fast 2L3"), ("isocell-3h1", "Component diagram / front Camera: ISOCELL Bright 3H1")]:
    claim("galaxy-s9-" + part, "samsung", part, "galaxy-s9", "component supplier", "galaxy-s9-components", ref + "; qualification: components may differ by country and carrier", "2026-09-10", customer_id="samsung", period="Historical Galaxy S9 component disclosure; publication date unavailable, retrieved September 2026.", uncertainty="Samsung identifies this sensor for Galaxy S9 but qualifies its list by country and carrier. Other sensor suppliers, exact variants, manufacturing facilities and production continuity remain unknown.")
claim("pico-w-rp2040", "raspberry-pi", "rp2040", "pico-w", "designer", "pico-w-launch", "Opening RP2040 description and Pico W introduction", "2022-06-30")
claim("pico-w-cyw43439", "infineon", "cyw43439", "pico-w", "component supplier", "pico-w-launch", "Wireless section / Infineon CYW43439 added to Pico W", "2022-06-30")
claim("pico2-rp2350", "raspberry-pi", "rp2350", "pico2", "designer", "pico2-launch", "Opening launch paragraph / RP2350 designed by Raspberry Pi", "2024-08-08")
claim("rp2350-fabrication", "tsmc", "rp2350", None, "fabricator", "rp2350-process", "Process discussion / continuing to use TSMC 40 nm", "2024-09-11", uncertainty="Part-level TSMC process evidence only. The exact fab, country, packaging site and allocation to each Pico 2 production period remain undisclosed; applying this to a product is an inference.")
for part, supplier in [("w25q32rv", "winbond"), ("abm8-272-t3", "abracon")]:
    claim("pico2-" + part, supplier, part, "pico2", "component supplier", "pico2-datasheet", "Page 4, About Raspberry Pi Pico 2 / external flash and crystal circuitry", "2026-07-03", period="Pico 2 datasheet revision July 3, 2026; earlier and later board batch sourcing not established.", uncertainty="Named in the reviewed datasheet revision. Manufacturing location, alternate approved devices and allocation across board revisions or batches remain unknown.")

if __name__ == "__main__":
    Path(__file__).with_name("collection.json").write_text(json.dumps(dict(entities=entities,sources=sources,claims=claims),indent=2)+"\n",encoding="utf-8")
