"""Manually reviewed public-interest aircraft research. No technical BOMs.

Narratives are released separately from manufacturing claims so leadership,
exhibition venues and externally visible systems never imply procurement edges.
"""
REVIEWED = "2026-09-10"


def source(id, title, url, publisher, published=None, access=""):
    return dict(id=id, title=title, url=url, publisher=publisher,
                published=published, retrieved=REVIEWED,
                license="Public reference; no open reuse licence asserted",
                terms_url=url, adapter="manual-reference",
                reuse="Short original factual paraphrases and citations only. Source-page rights notices apply; no source imagery, full text or technical tables redistributed. No automatic ingestion. " + access)


SOURCES = [
    source("m6-mehr-launch", "Iran starts mass production of advanced drone Mohajer-6", "https://en.mehrnews.com/photo/131926/Iran-starts-mass-production-of-advanced-drone-Mohajer-6", "Mehr News Agency", "2018-02-05"),
    source("m6-treasury-2023", "Treasury Sanctions Suppliers of Iranian UAVs Used to Target Ukraine’s Civilian Infrastructure", "https://home.treasury.gov/news/press-releases/jy1182", "U.S. Department of the Treasury", "2023-01-06"),
    source("m6-treasury-structure", "Treasury Sanctions Actors Supporting Iran’s Missile and UAV Programs", "https://home.treasury.gov/news/press-releases/jy1820", "U.S. Department of the Treasury", "2023-10-18"),
    source("m6-treasury-iaio", "Treasury Targets Enablers of Iran’s UAV Production", "https://home.treasury.gov/news/press-releases/jy2388", "U.S. Department of the Treasury", "2024-05-31"),
    source("m6-dia-visual", "Iranian UAVs in Ukraine: A Visual Comparison", "https://www.dia.mil/Portals/110/DIA_Iranian_UAVs_in_Ukraine-A_Visual_Comparison.pdf", "Defense Intelligence Agency", "2023-02-14", "Information cutoff: 2022-10-27. Printed page 7 / PDF page 9. Publication day verified by DIA's February 14 release notice (Article 3297418), which states the report was released that day. The PDF contains third-party copyrighted images; none are copied."),
    source("m6-dia-update", "DIA releases updated report on Russia’s use of lethal Iranian unmanned aerial vehicles in Ukraine", "https://www.dia.mil/News-Features/Articles/Article-View/Article/3504948/dia-releases-updated-report-on-russias-use-of-lethal-iranian-unmanned-aerial-ve/", "DIA Public Affairs", "2023-08-25"),
    source("m6-launch-report", "Iran announces mass production of bomb-carrying drones", "https://www.timesofisrael.com/iran-announces-mass-production-of-bomb-carrying-drones/", "The Times of Israel / Stuart Winer", "2018-02-06"),
    source("m6-ap-assessment", "US officials point to Russia using Iranian drones in Ukraine", "https://apnews.com/article/fecf53c964f09e24bd9a187715ac8598", "Associated Press", "2023-02-14", "Substantive search-index text reviewed; direct article retrieval was unavailable."),
    source("m6-odin", "Mohajer-6 Iranian Unmanned Aerial Vehicle (UAV)", "https://odin.t2com.army.mil/WEG/Asset/Mohajer-6_Iranian_Unmanned_Aerial_Vehicle_%28UAV%29", "U.S. Army ODIN", None, "Search-index entry reviewed; direct page timed out. Entry last modified 2024-11-13; original publication date unavailable. Only external form and the dating discrepancy are used."),
    source("m6-janes", "Iranian army deploys armed UAVs", "https://www.janes.com/defence-intelligence-insights/defence-news/iranian-army-deploys-armed-uavs", "Janes", None, "Publication date unavailable in the retrieved page; no year inferred from its July 17 event reference."),
    source("s238-janes-preview", "IRGC documentary shows jet-powered Shahed-136 UAV variant", "https://www.janes.com/defence-intelligence-insights/defence-news/air/irgc-documentary-shows-jet-powered-shahed-136-uav-variant", "Janes / Jeremy Binnie", "2023-10-03"),
    source("s238-twz-display", "Iran’s Jet-Powered Shahed Drone Could Be A Problem For Ukraine", "https://www.twz.com/irans-jet-powered-shahed-drone-could-be-a-problem-for-ukraine", "The War Zone / Thomas Newdick and Tyler Rogoway", "2023-11-22"),
    source("s238-tasnim-event", "Ayatollah Khamenei Briefed on IRGC Aerospace Advances", "https://www.tasnimnews.ir/en/news/2023/11/19/2992050/ayatollah-khamenei-briefed-on-irgc-aerospace-advances", "Tasnim News Agency", "2023-11-19"),
    source("shahed-treasury-organization", "Treasury Targets Actors Involved in Production and Transfer of Iranian Unmanned Aerial Vehicles to Russia for Use in Ukraine", "https://home.treasury.gov/news/press-releases/jy1104", "U.S. Department of the Treasury", "2022-11-15"),
    source("shahed-treasury-hajizadeh", "Treasury Targets Senior IRGC Commanders Behind Iran’s Destructive and Destabilizing Activities", "https://home.treasury.gov/news/press-releases/sm716", "U.S. Department of the Treasury", "2019-06-24"),
    source("shahed-treasury-aghajani", "Treasury Sanctions Network and Individuals in Connection with Iran’s Unmanned Aerial Vehicle Program", "https://home.treasury.gov/news/press-releases/jy0443", "U.S. Department of the Treasury", "2021-10-29"),
    source("s238-unn-unconfirmed", "The KFI does not confirm the information about the possible downing of a Shahed with a jet engine over Ukraine", "https://unn.ua/en/news/the-kfi-does-not-confirm-the-information-about-the-possible-downing-of-a-shahed-with-a-jet-engine-over-ukraine", "UNN / Zakhar Podkidyshev", "2024-01-09"),
    source("s238-unn-geran3", "DIU revealed foreign components and the filling of the Russian Geran-3 drone", "https://unn.ua/en/news/the-gur-revealed-foreign-parts-and-the-filling-of-the-russian-geran-3-drone", "UNN / Stepan Haftko", "2025-09-16", "Used only for Russian sample identity and the distinction from the Iranian aircraft. Technical parts and vendor findings are not reproduced."),
    source("s238-hrw", "Iran: Unlawful Strikes Across Gulf Endanger Civilians", "https://www.hrw.org/news/2026/03/17/iran-unlawful-strikes-across-gulf-endanger-civilians", "Human Rights Watch", "2026-03-17"),
    source("s238-csis", "Shahed-238", "https://missilethreat.csis.org/missile/shahed-238/", "CSIS Missile Defense Project", "2026-06-02", "Date is the profile update date. Used for attributed development and model identity, not aggregate performance, supplier or production claims."),
]


ENTITIES = [
    dict(id="aviation", kind="industry", name="Aviation", description="Aircraft program research. Major-system narratives are distinct from verified component and manufacturing claims."),
    dict(id="iran", kind="region", name="Iran", description="Country context. National origin does not establish a factory location."),
    dict(id="mohajer6", kind="product", name="Mohajer-6", aliases=["Mohajer 6", "Qods Mohajer-6", "Muhajer-6"], industry_id="aviation", description="Iranian multirole aircraft · dated program history and major-system research."),
    dict(id="shahed238", kind="product", name="Shahed-238", aliases=["Shahed 238"], industry_id="aviation", description="Iranian jet-powered one-way aircraft · November 2023 public debut and documented program context."),
    dict(id="qods-aviation", kind="company", name="Qods Aviation Industries", aliases=["QAI", "Qods Aviation Industries Company", "Light Airplanes Design and Manufacturing Industries"], industry_id="aviation", description="Organization attributed by U.S. Treasury to Mohajer-6 design and manufacture. Dated institutional context appears in the Mohajer-6 dossier. No factory is located from its address; this company is distinct from the IRGC Qods Force."),
    dict(id="shahed-aviation", kind="company", name="Shahed Aviation Industries Research Center", aliases=["SAIRC", "Shahed Aviation Industries"], industry_id="aviation", description="Shahed-family development organization. CSIS attributes Shahed-238 development to it; Treasury's 2022 institutional description predates this model's public display. Exact Shahed-238 final-assembly arrangements remain unverified."),
]

CLAIMS = [
    dict(id="mohajer6-qai-design", supplier_id="qods-aviation", product_id="mohajer6", role="designer", status="direct", observed_at="2023-01-06", period="U.S. Treasury attribution published January 6, 2023; current organization and production continuity unverified.", uncertainty="Direct means the cited source explicitly makes this attribution, not independent inspection. This is a whole-aircraft organizational attribution, not a complete parts list or proof of any factory location.", evidence=[dict(source_id="m6-treasury-2023", reference="Qods Aviation Industries section: Mohajer-6 design and manufacture attribution.")]),
    dict(id="mohajer6-qai-manufacture", supplier_id="qods-aviation", product_id="mohajer6", role="assembler", status="direct", observed_at="2023-10-18", period="Whole-aircraft manufacturer attribution in Treasury's October 18, 2023 release.", uncertainty="Treasury identifies QAI as manufacturer. The assembler role records whole-aircraft manufacture only; internal workshare, final-assembly line, production totals, subcontractors and current operating status are not established.", evidence=[dict(source_id="m6-treasury-structure", reference="Qods Aviation Industries section: manufacturer attribution and parent organization.")]),
    dict(id="shahed238-attributed-development", supplier_id="shahed-aviation", product_id="shahed238", role="designer", status="inferred", observed_at="2026-06-02", period="CSIS research profile updated June 2, 2026; not a factory disclosure.", uncertainty="Research assessment attributes development to Shahed Aviation Industries. Recorded conservatively as inferred, not independently verified production evidence. Shahed-family statements from 2022 cannot confirm this model's components, assembly or facilities.", evidence=[dict(source_id="s238-csis", reference="Development section: attribution to Shahed Aviation Industries; configuration and derivative boundaries retained.")]),
]


def entry(id, title, text, basis, date, *refs, entity_id=None):
    result = dict(id=id, title=title, text=text, basis=basis, date=date,
                  evidence=[dict(source_id=source_id, reference=reference) for source_id, reference in refs])
    if entity_id:
        result["entity_id"] = entity_id
    return result


MOHAJER = dict(
    product_id="mohajer6", reviewed=REVIEWED, subtitle="Multirole aircraft · historical research dossier",
    introduction="Follow the visible aircraft, the organizations behind the program, and the public record linking specific observed examples. Source assertions, direct observations and unresolved questions are identified individually below.",
    scope="Major-system and institutional research across the cited dates. This is a conceptual overview, not an engineering teardown, complete parts list or present-day production census. People are shown only in their dated public roles.",
    systems=[
        entry("m6-airframe", "Airframe and wings", "The Army ODIN reference describes a central fuselage and straight, high-mounted wings. These labels identify external form; neither the illustration nor this description establishes internal structure or materials.", "attributed", "Reference modified 2024-11-13", ("m6-odin", "General information / external configuration description; search-index access.")),
        entry("m6-tail", "Twin-boom tail", "Two tail booms and an elevated horizontal tail surface distinguish the external layout. DIA used the tail as one feature in its comparison of Iranian and recovered examples.", "observed", "DIA observation cutoff 2022-10-27", ("m6-odin", "External tail configuration."), ("m6-dia-visual", "Printed page 7: tail comparison.")),
        entry("m6-landing", "Wheeled undercarriage", "Wheeled landing gear is visible in the examples compared by DIA. The record supports this observable category, not a specification for every production configuration.", "observed", "DIA observation cutoff 2022-10-27", ("m6-dia-visual", "Printed page 7: landing-gear comparison.")),
        entry("m6-observation", "Observation equipment", "DIA identifies externally visible surveillance equipment in its comparison. Contemporary launch coverage also describes electro-optical observation equipment. The available observations do not identify all internal devices or establish uniformity across batches.", "observed", "2018 reporting / 2022 observations", ("m6-dia-visual", "Printed page 7: surveillance equipment."), ("m6-launch-report", "Description of observation equipment in launch reporting.")),
        entry("m6-ground", "Ground segment", "Janes' illustrated deployment reporting shows a separate control vehicle alongside the aircraft. The ground segment is therefore presented as its own system category, without suggesting that its hardware sits inside the airframe.", "observed", "Article publication date unavailable", ("m6-janes", "Image and description of the accompanying control vehicle.")),
    ],
    timeline=[
        entry("m6-early-date", "The first-unveiling date remains disputed", "Janes gives April 2016; the Army ODIN entry gives April 2017. The reviewed material does not resolve the discrepancy, so neither year is treated as settled.", "unresolved", "2016 / 2017", ("m6-janes", "Unveiling date in program background."), ("m6-odin", "Unveiling date in reference background.")),
        entry("m6-line-event", "Production-line inauguration reported", "Mehr's contemporaneous gallery reports a Mohajer-6 production-line opening in Tehran on February 5, 2018. This anchors the announced production milestone; it does not measure actual output.", "attributed", "2018-02-05", ("m6-mehr-launch", "Gallery introduction: inauguration, date and city.")),
        entry("m6-recovery", "Recovered aircraft enters the public evidence record", "DIA compared a largely intact aircraft recovered from the Black Sea in 2022 with examples pictured in Iran and Iraq, judging their visible features indistinguishable. This is an attributed identification of particular examples.", "attributed", "2022 observation / 2023-02 publication", ("m6-dia-visual", "Printed page 7; report information cutoff October 27, 2022.")),
        entry("m6-briefing", "U.S. assessment and Iranian account differ", "AP's account of the DIA briefing records the U.S. assessment of Iranian supply to Russia and Iran's position that a small number had been supplied before the invasion, with further supply denied. These positions remain separately attributed.", "context", "2023-02-14", ("m6-ap-assessment", "London briefing and account of Iran's stated position; search-index text.")),
        entry("m6-expanded-record", "DIA expands its evidence presentation", "DIA announced an updated report in August 2023 using recovered material and declassified imagery. Its coverage spans multiple aircraft families; an observation about one model cannot automatically populate another model's record.", "context", "2023-08-25", ("m6-dia-update", "Announcement of expanded report and its evidentiary scope.")),
    ],
    organizations=[
        entry("m6-qai", "Qods Aviation Industries", "Treasury attributes Mohajer-6 design and manufacture to QAI and records the Light Airplanes Design and Manufacturing Industries alias from mid-2020. The attribution is explicit; it is not a factory inspection.", "attributed", "2023-01-06", ("m6-treasury-2023", "QAI identity and manufacturer attribution."), entity_id="qods-aviation"),
        entry("m6-iaio", "Iran Aviation Industries Organization", "Treasury places QAI under Iran Aviation Industries Organization (IAIO), within the defense ministry structure. This is institutional oversight, not a component supply relationship. IAIO should not be confused with the similarly abbreviated Aerospace Industries Organization.", "attributed", "2023-10-18", ("m6-treasury-structure", "QAI subsidiary and IAIO/MODAFL relationship.")),
        entry("m6-modafl", "Ministry of Defense and Armed Forces Logistics", "MODAFL is the ministry named in Treasury's organizational account. A ministry's oversight does not establish which premises, workers or subcontractors produced an individual aircraft.", "context", "2023-10-18", ("m6-treasury-structure", "Institutional placement of QAI and IAIO.")),
        entry("m6-sibling-boundary", "HESA: a sibling is not a proven manufacturer here", "Treasury identifies QAI and HESA within IAIO's wider aviation organization. Shared institutional ownership alone does not establish that HESA assembled Mohajer-6; no such product edge is added.", "context", "2024-05-31", ("m6-treasury-iaio", "IAIO, QAI and HESA organization description.")),
    ],
    people=[
        entry("m6-hatami", "Amir Hatami", "Iranian defense minister at the reported production-line inauguration. Mehr identifies him as the official opening the line; that ceremonial role does not establish personal engineering authorship.", "attributed", "2018-02-05", ("m6-mehr-launch", "Named official at the inauguration.")),
        entry("m6-pakpour", "Mohammad Pakpour", "IRGC Ground Forces commander identified in contemporary reporting as attending the inauguration. Attendance is public-event context, not proof of factory management.", "context", "2018-02-05 event", ("m6-launch-report", "Officials attending the Tehran ceremony.")),
        entry("m6-ghoreishi", "Seyed Hojatollah Ghoreishi", "QAI board chairman in Treasury's dated leadership record. Current officeholding and individual design responsibilities are not asserted.", "attributed", "2023-01-06", ("m6-treasury-2023", "QAI leadership: chairman.")),
        entry("m6-damavandian", "Ghassem Damavandian", "QAI managing director and board member in Treasury's record. Its October release uses the spelling Ghasem; this is a name variant, not another manufacturer.", "attributed", "2023-01-06 / 2023-10-18", ("m6-treasury-2023", "QAI leadership: managing director."), ("m6-treasury-structure", "Ghasem Damavandian name spelling.")),
        entry("m6-board", "Other named QAI board members", "Treasury lists Hamidreza Sharifi-Tehrani, Reza Khaki, Majid Reza Niyazi-Angili and Vali Arlanizadeh as board members. These are historical organizational roles, not a list of product engineers.", "attributed", "2023-01-06", ("m6-treasury-2023", "Four further QAI directors.")),
        entry("m6-khajeh-fard", "Afshin Khajeh Fard", "Treasury names him as IAIO's chief in May 2024. The documented relationship is leadership of the parent organization; product-specific technical work is not established.", "attributed", "2024-05-31", ("m6-treasury-iaio", "IAIO leadership identification.")),
    ],
    manufacturing=[
        entry("m6-tehran-context", "Tehran: a historical production event", "Mehr places the 2018 line-opening ceremony in Tehran. The exact premises, surveyed location and later operating status are unresolved. A corporate address is not substituted for a verified product factory, and no map coordinate is assigned.", "attributed", "2018-02-05", ("m6-mehr-launch", "City and inauguration event; no precise premises established.")),
        entry("m6-workshare", "Manufacturer attribution has a narrower meaning", "Treasury's QAI attribution does not describe internal workshare, supplier contracts, batch allocations or an exclusive final-assembly line. The network records the attributed organization while leaving facility fields empty.", "unresolved", "2023-10-18 source scope", ("m6-treasury-structure", "Manufacturer attribution; no batch-level factory allocation supplied.")),
    ],
    assessment=[
        entry("m6-sample-limits", "An observed aircraft is not an entire production series", "DIA's comparison supports an origin assessment for the pictured examples. It cannot establish a complete inventory, every variant, or continuity of production. Its October 2022 information cutoff also predates the Shahed-238 display.", "context", "2022-10-27 cutoff", ("m6-dia-visual", "Report scope, cutoff and Mohajer-6 visual comparison.")),
        entry("m6-date-limits", "Source dates and current status are different", "The 2018 event report and subsequent institutional records describe different moments. They do not establish that the same line remains active today. The dossier preserves those dates instead of presenting a live factory or personnel registry.", "unresolved", "2018–2024 records", ("m6-mehr-launch", "Historical inauguration only."), ("m6-treasury-iaio", "Dated organizational record.")),
    ],
)

SHAHED = dict(
    product_id="shahed238", reviewed=REVIEWED, subtitle="Jet-powered one-way aircraft · historical research dossier",
    introduction="Examine the public display, attributed development organization and evolving identification record. Exhibition configurations and later Russian derivative reporting remain separately scoped throughout this dossier.",
    scope="Exterior and major-system categories only. Displayed options are not a unified production configuration, and Russian Geran-3 findings are not an Iranian Shahed-238 parts list. Leadership and venue records are dated institutional context.",
    systems=[
        entry("s238-airframe", "Delta-wing airframe", "The 2023 display imagery shows a delta-wing exterior in a matte dark finish. An observed finish is not evidence of a particular coating technology or verified performance.", "observed", "2023-11-19 display", ("s238-twz-display", "Original analysis of exhibition imagery and visible finish.")),
        entry("s238-propulsion", "Jet propulsion", "The November display analysis identifies the named Shahed-238 as jet-powered. This supports the broad propulsion category; no engine model, construction detail or performance figure is inferred here.", "observed", "2023-11-19 display", ("s238-twz-display", "Named Shahed-238 identification and broad jet-propulsion category.")),
        entry("s238-flight", "Flight-management systems", "Public analysis discusses differing avionics configurations, but the exhibition did not establish one verified internal arrangement for all aircraft. This card represents a system category, not a located assembly or shared production design.", "unresolved", "2023-11 reporting", ("s238-twz-display", "Configuration discussion and explicit uncertainty about implementation and maturity.")),
        entry("s238-configurations", "Displayed configuration options", "Three examples were displayed. The reviewed analysis leaves their testing, availability and configuration maturity uncertain. They must not be combined into a single aircraft containing every announced option.", "observed", "2023-11-19 display", ("s238-twz-display", "Three displayed examples and uncertainty about fielding.")),
    ],
    timeline=[
        entry("s238-precursor", "An unnamed jet aircraft appears on film", "Janes examined footage from a documentary premiered on September 26, 2023. The aircraft was unnamed in the trailer; the footage is a precursor observation, not a verified Shahed-238 naming date.", "observed", "2023-09-26", ("s238-janes-preview", "Documentary premiere and unnamed aircraft.")),
        entry("s238-debut", "Named public display in Tehran", "The War Zone identifies the November 19 exhibition as the public Shahed-238 display. Tasnim independently records the exhibition visit and Tehran venue. A public display establishes visibility, not serial-production output.", "attributed", "2023-11-19", ("s238-twz-display", "Shahed-238 public display identification."), ("s238-tasnim-event", "Exhibition date and venue.")),
        entry("s238-initial-claims", "Early identification was not immediately confirmed", "UNN interviewed forensic-institute director Oleksandr Ruvin, who said his institute's research had not established Shahed-238 use at that point. This dated absence of confirmation does not disprove later observations.", "attributed", "2024-01-09", ("s238-unn-unconfirmed", "Direct interview with Oleksandr Ruvin about the institute's findings at that date.")),
        entry("s238-russian-sample", "A Russian derivative needs its own evidence scope", "UNN reports Ukrainian intelligence's examination of a Russian Geran-3 U-series sample. Its relationship to Shahed-238 does not make the sample's internals, suppliers or manufacturing arrangements evidence for the Iranian aircraft.", "attributed", "2025-09-16", ("s238-unn-geran3", "Russian sample identity and distinction from Iranian design.")),
        entry("s238-civilian-impact", "Civilian-impact investigation", "Human Rights Watch identifies a Shahed-238 in a February 28, 2026 Dubai hotel-forecourt incident and relays local authorities' report of four injuries. The investigation concerns civilian harm, not manufacturing attribution; HRW could not rule out military guests at the hotel.", "attributed", "2026-02-28 event / 2026-03-17 report", ("s238-hrw", "Dubai hotel investigation, aircraft identification and limits.")),
    ],
    organizations=[
        entry("s238-sairc", "Shahed Aviation Industries Research Center", "CSIS attributes Shahed-238 development to Shahed Aviation Industries. This is a research assessment, not a manufacturer declaration or final-assembly inspection, so the supply-network development edge is conservatively marked inferred.", "attributed", "2026-06-02 profile update", ("s238-csis", "Development attribution to Shahed Aviation Industries."), entity_id="shahed-aviation"),
        entry("s238-asf", "IRGC Aerospace Force", "Treasury described SAIRC as subordinate to the IRGC Aerospace Force in November 2022. That institutional record predates Shahed-238's named display and cannot independently establish this model's manufacturer workshare.", "context", "2022-11-15", ("shahed-treasury-organization", "Shahed Aviation Industries Research Center institutional description.")),
        entry("s238-host", "Ashura Aerospace University", "Tasnim identifies the university in Tehran as the exhibition venue. Its presence in the public record is as a host location; no Shahed-238 manufacturing relationship is established.", "context", "2023-11-19", ("s238-tasnim-event", "Location of the IRGC Aerospace Force exhibition.")),
    ],
    people=[
        entry("s238-khamenei", "Ali Khamenei", "Tasnim records his visit to the exhibition as supreme leader and commander-in-chief in November 2023. This entry describes that dated public role, not product engineering authorship or present officeholding.", "context", "2023-11-19", ("s238-tasnim-event", "Exhibition visitor and public role at the event.")),
        entry("s238-hajizadeh", "Amir Ali Hajizadeh", "Treasury identifies Hajizadeh as IRGC Aerospace Force commander in 2019; Janes identifies him in that role in the 2023 documentary. Neither record establishes that he personally designed Shahed-238.", "context", "2019-06-24 / 2023-10-03", ("shahed-treasury-hajizadeh", "Dated command role."), ("s238-janes-preview", "Documentary interview participant and command role.")),
        entry("s238-aghajani", "Saeed Aghajani", "Treasury names Aghajani as IRGC Aerospace Force UAV Command commander in October 2021. This provides earlier institutional context; no product-specific Shahed-238 development role is established.", "context", "2021-10-29", ("shahed-treasury-aghajani", "Dated UAV Command leadership identification.")),
        entry("s238-engineers", "Product-specific engineers remain unverified", "The reviewed development assessment names an organization, not a verified engineering team. Public commanders and exhibition attendees should not be converted into designer or supplier records.", "unresolved", "2026-06-02 source scope", ("s238-csis", "Organizational development attribution without individual engineering credits.")),
    ],
    manufacturing=[
        entry("s238-venue-boundary", "A Tehran exhibition venue is not a factory", "The November 2023 venue establishes where the aircraft was shown. It supplies no proof of final assembly there. No military-site coordinates or factory marker are assigned.", "context", "2023-11-19", ("s238-tasnim-event", "Exhibition venue only.")),
        entry("s238-assembly-gap", "Iranian final assembly remains unresolved", "The reviewed CSIS profile does not provide independently verified, product-specific Iranian final-assembly premises or workshare. General Shahed-family manufacturing statements are insufficient to fill that gap.", "unresolved", "2026-06-02 profile scope", ("s238-csis", "Development/manufacturing discussion lacks independently verified Iranian site allocation.")),
        entry("s238-derivative-boundary", "Geran-3 observations stay with the Russian sample", "The reported Geran-3 examination concerns a distinct Russian sample. Transferring its plant, companies or hardware findings to every Iranian Shahed-238 would erase the very provenance distinctions this collection preserves.", "context", "2025-09-16", ("s238-unn-geran3", "Russian sample examination and separate production context.")),
    ],
    assessment=[
        entry("s238-family-boundary", "Shahed is a family name, not a shared parts list", "Treasury's 2022 family-level account predates the named Shahed-238 display. It supports institutional background only. Shahed-131, Shahed-136 and Geran-2 claims therefore do not automatically become Shahed-238 dependencies.", "context", "2022 record / 2023 model display", ("shahed-treasury-organization", "Earlier Shahed-family scope."), ("s238-twz-display", "Named Shahed-238 display in November 2023.")),
        entry("s238-observation-history", "Identification changed as evidence accumulated", "The January 2024 interview records uncertainty at one institute at one time. Later Russian-sample reporting and HRW's 2026 identification concern different observations; none retroactively verifies every earlier claim.", "context", "2024–2026", ("s238-unn-unconfirmed", "Dated lack of institute confirmation."), ("s238-unn-geran3", "Later Russian sample report."), ("s238-hrw", "Separate 2026 incident identification.")),
    ],
)

DOSSIERS = [MOHAJER, SHAHED]
