"""Reviewed LUCAS public-interest dossier and scoped organizational attributions.

Exterior categories are not an engineering teardown. Government program,
evaluation and oversight relationships remain separate from supplier claims.
"""

REVIEWED = "2026-09-10"


def source(id, title, url, publisher, published=None, access=""):
    return dict(
        id=id, title=title, url=url, publisher=publisher,
        published=published, retrieved=REVIEWED,
        license="Public reference; no open reuse licence asserted",
        terms_url=url, adapter="manual-reference",
        reuse="Original factual paraphrases and precise citations only. Source-page rights notices apply; no source imagery, full text or technical tables redistributed. No automatic ingestion. " + access,
    )


SOURCES = [
    source("lucas-spektre-about", "About SpektreWorks", "https://spektreworks.com/about/", "SpektreWorks", access="Undated company self-description, reviewed September 10, 2026. City-level corporate context only; no factory inferred."),
    source("lucas-spektre-target", "Counter UAS — FLM 136", "https://spektreworks.com/counter-uas/", "SpektreWorks", access="Undated live catalog. Used only to identify the separately marketed FLM 136 threat-emulation platform. Its technical specifications are not transferred to LUCAS."),
    source("lucas-spektre-services", "Custom Engineering", "https://spektreworks.com/custom-engineering/", "SpektreWorks", access="Undated company-wide services page. A capability or software mentioned here is not evidence of a LUCAS supplier relationship."),
    source("lucas-pentagon-showcase", "Pentagon Showcases Rapidly Developed Drones", "https://www.nationaldefensemagazine.org/articles/2025/8/15/pentagon-showcases-rapidly-developed-drones", "National Defense / Sabina Lum", "2025-08-15", "Firsthand showcase reporting and direct emailed comments from Dan Ermer. Used for observed exterior, developer attribution and the named official's development-policy role; advertised configurations are not assumed deployed."),
    source("lucas-pentagon-event", "SD, USD(R&E) Tour Multi-Domain Autonomous Displays at Pentagon", "https://www.dvidshub.net/image/9183292/sd-usdre-tour-multi-domain-autonomous-displays-pentagon", "Office of the Secretary of Defense Public Affairs / Alexander Kubitza via DVIDS", "2025-07-16", "Photo ID 9183292; VIRIN 250716-D-PM193-1138. Caption and metadata establish the event date and public roles. The image is not redistributed."),
    source("lucas-apfit-funding", "APFIT Program Boosts Small Business Innovation with Record Funding Level", "https://www.cto.mil/news/apfit-sbi/", "Defense Research & Engineering", "2025-06-17", "Dated release and FY2025 project list reviewed in full. The list assigns $30 million to the Marine Corps LUCAS project; it does not name an awardee, publish a contract identifier or establish payments to SpektreWorks. The live page now uses OUSW branding despite its June 2025 release date; the dossier uses the neutral Research & Engineering office label."),
    source("lucas-rejtf-establishment", "CENTCOM Launches Innovation Joint Task Force to Rapidly Equip Warfighters", "https://www.centcom.mil/MEDIA/PUBLIC-RELEASES/Article/4312394/centcom-launches-innovation-joint-task-force-to-rapidly-equip-warfighters/", "U.S. Central Command", "2025-09-23", "Release 20250923-01. Establishes the dated innovation organization and its relationship to CENTCOM. This September release does not name LUCAS; the subsequent December release separately supports the Scorpion Strike alignment."),
    source("lucas-centcom-components", "CENTCOM Components", "https://www.centcom.mil/ABOUT-US/COMPONENT-COMMANDS/", "U.S. Central Command", access="Undated official component directory, reviewed September 10, 2026. Used only for the SOCCENT component relationship. Review date is not an establishment date; unrelated geographic descriptions and personnel locations are omitted."),
    source("lucas-tf59-establishment", "U.S. 5th Fleet Launches New Task Force to Integrate Unmanned Systems", "https://www.navy.mil/Press-Office/News-Stories/display-news/Article/2768479/us-5th-fleet-launches-new-task-force-to-integrate-unmanned-systems/", "U.S. Naval Forces Central Command / U.S. 5th Fleet / Roland Franklin", "2021-09-09", "Original establishment announcement and commissioning caption. This institutional history predates LUCAS; the later December 2025 naval release establishes the aircraft-specific demonstration. Precise installation geography is omitted."),
    source("lucas-centcom-squadron", "U.S. Launches One-Way-Attack Drone Force in the Middle East", "https://www.centcom.mil/MEDIA/PUBLIC-RELEASES/Article/4347030/us-launches-one-way-attack-drone-force-in-the-middle-east/", "U.S. Central Command", "2025-12-03", "Release 20251203-01. Included photograph captions are dated November 23, 2025; the announcement is December 3. Broad regional context only."),
    source("lucas-yuma-evaluation", "Low-cost combat attack system tested at U.S. Army Yuma Proving Ground", "https://www.dvidshub.net/news/552807/low-cost-combat-attack-system-tested-us-army-yuma-proving-ground", "U.S. Army Yuma Proving Ground / Mark Schauer via DVIDS", "2025-12-03", "Story 552807. Dated account of a particular evaluation using inert payloads; it is not a declaration about every aircraft or later deployed configuration. Precise installation geography and test procedures are not reproduced."),
    source("lucas-navy-sea", "U.S. Navy in Middle East Employs Attack Drone at Sea for First Time", "https://www.navy.mil/Press-Office/News-Stories/display-news/Article/4363707/us-navy-in-middle-east-employs-attack-drone-at-sea-for-first-time/", "U.S. Naval Forces Central Command Public Affairs", "2025-12-18", "Navy page publication is December 18; the described event and photograph captions are December 16. Operator and event context only, without launch procedures or hardware specifications."),
    source("lucas-centcom-epic", "U.S. Forces Launch Operation Epic Fury", "https://www.centcom.mil/MEDIA/PUBLIC-RELEASES/Article/4418396/us-forces-launch-operation-epic-fury/", "U.S. Central Command", "2026-02-28", "Command's contemporaneous account. The paragraph names Task Force Scorpion Strike's one-way drones rather than specifying a LUCAS configuration. The older PRESS-RELEASES URL returned a generic media index; this PUBLIC-RELEASES URL resolves the article."),
    source("lucas-senate-transcript", "To receive testimony on the American small drone industrial base — transcript", "https://www.armed-services.senate.gov/imo/media/doc/full-transcript_03-03-2026.pdf", "U.S. Senate Committee on Armed Services", "2026-03-05", "Hearing date verified on the PDF title page and official hearing page: March 5, despite March 3 in the filename. Printed pages 5 and 60–62 are used. The transcript renders Marks' given name as Stephen; the official witness listing identifies Steven M. Marks."),
    source("lucas-senate-hearing", "To receive testimony on the American small drone industrial base", "https://www.armed-services.senate.gov/hearings/to-receive-testimony-on-the-american-small-drone-industrial-base", "U.S. Senate Committee on Armed Services", "2026-03-05", "Official event date and witness listing. Used for Steven M. Marks' name and dated public institutional role."),
    source("lucas-reuters-production", "US debuts LUCAS kamikaze drone in Iran after fast-tracked Pentagon procurement", "https://www.channelnewsasia.com/world/us-military-lucas-kamikaze-drone-iran-pentagon-weapon-5967021", "Reuters via CNA", "2026-03-04", "Full syndicated article reviewed; CNA HTML datePublished is 2026-03-04T16:03:00+08:00. Original reporting includes anonymous program sources; SpektreWorks declined comment. Only whole-aircraft manufacturer/design-ownership attribution is recorded in the network. Suggested subsystem vendors and operational configurations are not reproduced."),
    source("lucas-uk-answer", "USA: Uncrewed Systems — Written Answer 118990", "https://qna.files.parliament.uk/qnadailyreports/Written-Questions-Answers-Statements-Daily-Report-Commons-2026-03-17.pdf", "UK House of Commons / Ministry of Defence", "2026-03-17", "Daily Report, printed page 39: Ben Obese-Jecty's question and Luke Pollard's answer. This is a dated statement about records of formal engagement, not a universal claim that no contacts ever occurred."),
    source("lucas-centcom-falcon", "CENTCOM Launches First-Ever Multinational Attack Drone Task Force", "https://www.centcom.mil/MEDIA/PUBLIC-RELEASES/Article/4573159/centcom-launches-first-ever-multinational-attack-drone-task-force/", "U.S. Central Command", "2026-08-13", "Current review includes this later institutional announcement. It concerns a wider multi-domain task force; it does not establish LUCAS exports, named partner purchases or additional aircraft suppliers."),
]


ENTITIES = [
    dict(id="lucas", kind="product", name="LUCAS", aliases=["Low-Cost Uncrewed Combat Attack System", "Low-cost Unmanned Combat Attack System"], industry_id="aviation", description="U.S. one-way aircraft program · cited industrial attributions, public program history and conceptual major-system exploration."),
    dict(id="spektreworks", kind="company", name="SpektreWorks", aliases=["SpektreWorks, Inc.", "Spektreworks Inc."], industry_id="aviation", description="Arizona unmanned-systems company attributed to LUCAS development and manufacture in dated original reporting. Corporate services, FLM 136 target-drone specifications and government program partners are not a verified LUCAS parts list."),
]


CLAIMS = [
    dict(id="lucas-spektreworks-development", supplier_id="spektreworks", product_id="lucas", role="designer", status="direct", observed_at="2025-08-15", period="Developer attribution in National Defense's August 15, 2025 firsthand showcase reporting.", uncertainty="The source explicitly attributes LUCAS development to SpektreWorks. Direct denotes an explicit published attribution, not an independent design audit. It does not establish individual engineers, all development workshare, component suppliers or a production site.", evidence=[dict(source_id="lucas-pentagon-showcase", reference="LUCAS paragraphs: developer attribution; direct event reporting and Dan Ermer comments.")]),
    dict(id="lucas-spektreworks-manufacture", supplier_id="spektreworks", product_id="lucas", role="assembler", status="direct", observed_at="2026-03-04", period="Reuters manufacturer and manufacturing-contract attribution, published by CNA March 4, 2026.", uncertainty="Assembler records whole-aircraft manufacture only. Reuters identifies SpektreWorks; the company declined comment. The article does not publish contract identifiers, batch allocations, final-assembly premises, subcontractor workshare or a complete manufacturer census.", evidence=[dict(source_id="lucas-reuters-production", reference="Opening manufacturer attribution and Rapid Deployment section: SpektreWorks manufacturing contracts.")]),
]


def entry(id, title, text, basis, date, *refs, entity_id=None):
    result = dict(id=id, title=title, text=text, basis=basis, date=date,
                  evidence=[dict(source_id=source_id, reference=reference) for source_id, reference in refs])
    if entity_id:
        result["entity_id"] = entity_id
    return result


def relationship(id, source_node, target_node, relation_kind, title, text, basis, date, *refs, entity_id=None):
    return {**entry(id, title, text, basis, date, *refs, entity_id=entity_id),
            "source_node": source_node, "target_node": target_node, "relation_kind": relation_kind}


LUCAS = dict(
    product_id="lucas", reviewed=REVIEWED,
    subtitle="U.S. one-way aircraft · industry and public-program dossier",
    introduction="Explore the aircraft's visible form, its attributed U.S. developer and manufacturer, and the organizations that funded, evaluated and fielded the program. The dated record follows the June 2025 project-funding announcement through broader task-force developments announced in August 2026.",
    scope="Conceptual exterior and major-system overview with high-level weapons-role context. This is not an engineering teardown or a complete supplier census. Test examples, fielded aircraft and related target platforms retain their own evidence boundaries; people appear only in dated public roles.",
    systems=[
        entry("external-airframe", "External airframe", "Pentagon showcase reporting describes delta wings and a rounded nose, while noting that prototype features could change. The exterior establishes neither internal assemblies nor materials.", "observed", "July 2025 display / 2025-08-15 report", ("lucas-pentagon-showcase", "LUCAS display paragraphs: delta wings, rounded nose and prototype-change caveat.")),
        entry("propulsion", "Propulsion exterior", "CENTCOM's November photographs show an aft propeller. This visible feature supports a propulsion category, not a verified engine model or component manufacturer.", "observed", "2025-11-23 photographs / 2025-12-03 release", ("lucas-centcom-squadron", "Official photographs 251123-D-D0477-1163 and 251123-D-D0477-1029: externally visible aft propeller.")),
        entry("guidance-control", "Guidance and control", "CENTCOM describes autonomous operation at a broad level. The Senate's later public exchange did not disclose the internal implementation. This topic therefore shows a system category without locating avionics or asserting a specific decision-making architecture.", "attributed", "2025-12-03 / 2026-03-05", ("lucas-centcom-squadron", "Broad autonomy description."), ("lucas-senate-transcript", "Printed page 60: Marks declines to discuss LUCAS internals in the open hearing.")),
        entry("payload-role", "Weapons and payload role", "LUCAS is described as a one-way attack aircraft. Yuma's December evaluation report specifically describes inert payloads and a weapons payload still under development in that test context. Later fielding does not make that test configuration a universal weapons specification.", "attributed", "2025-12-03 evaluation account", ("lucas-yuma-evaluation", "Opening paragraphs: one-way role, inert evaluation payloads and dated development status.")),
        entry("ground-support", "Ground and launch support", "The Navy's reported shipboard demonstration establishes a support segment outside the aircraft. The visual treats this as a separate topic, without suggesting that a ship, launcher or control station is an internal aircraft component.", "context", "2025-12-16 event", ("lucas-navy-sea", "Shipboard demonstration and Task Force 59 participation.")),
    ],
    timeline=[
        entry("lucas-june-funding", "A documented production-transition investment", "The official FY2025 APFIT list assigns $30 million to the Marine Corps LUCAS project. This is project-level funding, not a unit price, delivery count or identified company contract.", "attributed", "2025-06-17", ("lucas-apfit-funding", "FY2025 funded-project list: Low-cost Uncrewed Combat Attack Systems, $30 million, U.S. Marine Corps.")),
        entry("lucas-july-showcase", "Pentagon public showcase", "Official metadata dates the Pentagon tour to July 16; National Defense identifies LUCAS among the prototypes. A display establishes visibility, not completed fleet certification.", "observed", "2025-07-16", ("lucas-pentagon-event", "Photo caption and event date."), ("lucas-pentagon-showcase", "LUCAS among the displayed prototypes.")),
        entry("lucas-september-program", "A joint innovation framework", "CENTCOM established the Rapid Employment Joint Task Force on September 23. This announcement describes the innovation framework; LUCAS and Scorpion Strike enter its public record later.", "context", "2025-09-23", ("lucas-rejtf-establishment", "Release 20250923-01: establishment date and organizational purpose.")),
        entry("lucas-squadron-announcement", "The squadron enters the official record", "CENTCOM announced Task Force Scorpion Strike on December 3. The accompanying LUCAS photographs carry November 23 dates; photograph dates and announcement dates describe different events.", "attributed", "2025-11-23 / 2025-12-03", ("lucas-centcom-squadron", "Release date and photograph captions.")),
        entry("lucas-yuma-milestone", "Yuma evaluation disclosed", "The Army published its Yuma evaluation account separately from the squadron announcement. The two reports do not establish identical configurations.", "attributed", "2025-12-03", ("lucas-yuma-evaluation", "Dated evaluation account; separate source scope from the squadron announcement.")),
        entry("lucas-sea-milestone", "First reported naval demonstration", "The Navy reported its first LUCAS launch from a naval vessel on December 16 aboard USS Santa Barbara. The report was published two days later.", "attributed", "2025-12-16 / 2025-12-18", ("lucas-navy-sea", "Event date, named vessel and page publication date.")),
        entry("lucas-combat-announcement", "First combat-use announcement", "CENTCOM reported that Scorpion Strike used one-way drones in combat for the first time during Operation Epic Fury. The release does not specify their configuration; the Senate subsequently identified LUCAS in its account of that milestone.", "attributed", "2026-02-28 / 2026-03-05", ("lucas-centcom-epic", "Final paragraphs: task force's first combat use."), ("lucas-senate-transcript", "Printed page 5: chairman's LUCAS identification.")),
        entry("lucas-august-context", "The wider task-force program evolves", "CENTCOM announced plans for multinational Task Force Falcon Strike, drawing on Scorpion Strike's experience. The announcement expands the institutional story; it does not identify new LUCAS manufacturers or confirm aircraft transfers to particular partner countries.", "context", "2026-08-13", ("lucas-centcom-falcon", "Falcon Strike announcement, consultation status and Scorpion Strike background.")),
    ],
    organizations=[
        entry("lucas-spektreworks", "SpektreWorks", "National Defense names SpektreWorks as developer. The Arizona company's own description covers unmanned-systems engineering and production, without identifying individual LUCAS engineering workshare.", "attributed", "2025-08-15 / company page reviewed 2026-09-10", ("lucas-pentagon-showcase", "LUCAS developer attribution."), ("lucas-spektre-about", "Company self-description."), entity_id="spektreworks"),
        entry("lucas-marine-sponsor", "U.S. Marine Corps", "Yuma's report identifies Marine Corps sponsorship of the evaluated aircraft. It does not assign the service manufacturing workshare.", "attributed", "2025-12-03", ("lucas-yuma-evaluation", "Opening program description: Marine Corps sponsorship.")),
        entry("lucas-research-office", "Research & Engineering and APFIT", "Research & Engineering's APFIT program supports transition into production. Its June announcement explicitly includes LUCAS, connecting public funding to the industrial story without identifying a component supplier.", "context", "2025-06-17", ("lucas-apfit-funding", "Program ownership, production-transition purpose and FY2025 LUCAS project listing.")),
        entry("lucas-centcom-soccent", "CENTCOM and SOCCENT", "SOCCENT personnel led the squadron effort introduced by CENTCOM. These command roles are separate from manufacturing.", "attributed", "2025-12-03", ("lucas-centcom-squadron", "Task Force Scorpion Strike and SOCCENT personnel.")),
        entry("lucas-navcent-tf59", "NAVCENT / Fifth Fleet and Task Force 59", "The Navy identifies Task Force 59 as the naval organization that conducted the demonstration, within NAVCENT/Fifth Fleet. Its involvement records an operator and demonstration partner, not an aircraft assembler.", "attributed", "2025-12-18", ("lucas-navy-sea", "Task Force 59 and NAVCENT organizational attribution.")),
    ],
    people=[
        entry("lucas-showcase-leaders", "Pete Hegseth and Emil Michael", "The official July 16 caption identifies Hegseth as defense secretary and Michael as under secretary for research and engineering during the showcase tour. These are dated public leadership roles, not individual engineering credits.", "context", "2025-07-16", ("lucas-pentagon-event", "Named officials and roles in the event caption.")),
        entry("lucas-ermer", "Dan Ermer", "National Defense identifies Ermer as mission-capabilities director for rapid prototyping and experimentation. His direct comments describe early affordability constraints, not individual engineering authorship.", "attributed", "2025-08-15", ("lucas-pentagon-showcase", "Direct emailed comments and public official's title.")),
        entry("lucas-law", "Nicholas Law", "Yuma identifies Colonel Law as the research-and-engineering office's experimentation director, commenting on evaluation and production aspirations.", "attributed", "2025-12-03", ("lucas-yuma-evaluation", "Named experimentation official and quoted role.")),
        entry("lucas-cooper", "Brad Cooper", "CENTCOM names Admiral Cooper as its commander in the squadron announcement. The entry records command sponsorship, not personal authorship of the aircraft.", "context", "2025-12-03", ("lucas-centcom-squadron", "Named command role in the announcement.")),
        entry("lucas-renshaw", "Curt Renshaw", "The naval release identifies Vice Admiral Renshaw as NAVCENT/Fifth Fleet commander commenting on the demonstration. His public role does not establish industrial design responsibility.", "context", "2025-12-18", ("lucas-navy-sea", "Named NAVCENT/Fifth Fleet commander.")),
        entry("lucas-marks", "Steven M. Marks", "The Senate's official witness list identifies Major General Marks as director of the Defense Autonomous Warfare Group. His hearing appearance provides public oversight context; it does not establish that his organization supplied LUCAS hardware.", "context", "2026-03-05", ("lucas-senate-hearing", "Official witness name, organization and hearing date.")),
    ],
    manufacturing=[
        entry("lucas-manufacturer-record", "Whole-aircraft manufacturing attribution", "Reuters identifies SpektreWorks as manufacturer and reports that it held manufacturing contracts; the company declined comment. The app records that explicit attribution without presenting it as an independently inspected production line.", "attributed", "2026-03-04", ("lucas-reuters-production", "Opening attribution and Rapid Deployment section."), entity_id="spektreworks"),
        entry("lucas-design-ownership", "Reported government design ownership", "Reuters reports government ownership of the LUCAS design intellectual property. This could permit other manufacturers; it does not prove that an additional named firm produced a delivered aircraft, or establish the terms of a license.", "attributed", "2026-03-04", ("lucas-reuters-production", "Design intellectual-property ownership and multiple-manufacturer possibility.")),
        entry("lucas-production-aspiration", "Multiple producers were an objective", "Yuma describes an intention to enable multiple manufacturers, without naming additional producers or verifying output. This remains an aspiration.", "attributed", "2025-12-03", ("lucas-yuma-evaluation", "Law's multiple-manufacturer aspiration.")),
        entry("lucas-test-facility", "Yuma is an evaluation venue", "The Army establishes testing at Yuma, without assigning airframe manufacture there. Consequently the installation receives no supplier-factory edge.", "context", "2025-12-03", ("lucas-yuma-evaluation", "Evaluation venue and source scope.")),
        entry("lucas-arizona-context", "Arizona corporate context", "SpektreWorks describes itself as Phoenix-based. A city-level company description does not locate a LUCAS final-assembly line. Exact premises, audited production capacity and batch-level facility allocation remain unverified in the reviewed record.", "unresolved", "Company page reviewed 2026-09-10", ("lucas-spektre-about", "Corporate self-description, without a product-specific plant allocation.")),
        entry("lucas-services-boundary", "Company capabilities are not a parts list", "SpektreWorks advertises mechanical, electrical, software and flight services. That business-wide capability menu does not identify what was installed in a delivered LUCAS aircraft or establish a contract with any specific component company.", "context", "Services page reviewed 2026-09-10", ("lucas-spektre-services", "Company-wide service categories; no LUCAS configuration attribution.")),
    ],
    assessment=[
        entry("lucas-flm-boundary", "FLM 136 remains a separate catalog platform", "SpektreWorks markets FLM 136 for threat emulation and counter-drone testing. Its catalog specification is not labeled as a verified fielded LUCAS configuration. Shared ancestry or resemblance therefore does not justify transferring its technical parts or performance figures.", "context", "Catalog reviewed 2026-09-10", ("lucas-spektre-target", "FLM 136 identity and threat-emulation scope.")),
        entry("lucas-shahed-boundary", "Shahed-136 lineage is not a supply relationship", "The Senate chairman describes LUCAS as derived through reverse engineering of Shahed-136. That historical attribution concerns Shahed-136, not Shahed-238, and does not establish an Iranian company as a supplier to the U.S. program.", "attributed", "2026-03-05", ("lucas-senate-transcript", "Printed page 5: explicitly names Shahed-136.")),
        entry("lucas-oversight-boundary", "Public questions did not disclose the internals", "Senator Mark Kelly asked about LUCAS decision-making and oversight. Marks offered a classified briefing instead of public technical detail. The unanswered questions must not be treated as confirmation of a particular autonomous weapons architecture.", "unresolved", "2026-03-05", ("lucas-senate-transcript", "Printed pages 60–62: question, response and oversight discussion.")),
        entry("lucas-industrial-scale", "Wider drone targets are not LUCAS orders", "The Senate distinguishes the Drone Dominance effort for smaller aircraft from broader autonomous-warfare work. Aggregate program ambitions cannot be converted into LUCAS purchase quantities, current inventory or SpektreWorks production totals.", "context", "2026-03-05", ("lucas-senate-transcript", "Printed pages 4–5: distinct program scopes.")),
        entry("lucas-uk-engagement", "An allied relationship remains unestablished", "In a written answer, UK minister Luke Pollard said the department held no records of formal LUCAS engagement with U.S. counterparts or SpektreWorks. This dated records statement supports leaving a UK program edge absent; it does not rule out all informal contact or later change.", "attributed", "2026-03-17", ("lucas-uk-answer", "Printed page 39, answer 118990.")),
        entry("lucas-latest-boundary", "A larger task force does not identify every aircraft", "The August Falcon Strike announcement discusses a wider mix of aerial and maritime systems and planned partner participation. It does not establish that every task-force activity uses LUCAS or identify new LUCAS factories, subcontractors or export customers.", "context", "2026-08-13", ("lucas-centcom-falcon", "Multi-domain scope and invitation process; no product-specific manufacturer census.")),
    ],
    network=dict(
        nodes=[
            dict(id="lucas", label="LUCAS", kind="product"),
            dict(id="spektreworks", label="SpektreWorks", kind="company"),
            dict(id="marine-corps", label="U.S. Marine Corps", kind="organization"),
            dict(id="yuma-evaluation", label="Yuma Proving Ground", kind="test-center"),
            dict(id="soccent", label="SOCCENT", kind="organization"),
            dict(id="scorpion-strike", label="Task Force Scorpion Strike", kind="program"),
            dict(id="task-force-59", label="Task Force 59", kind="organization"),
            dict(id="centcom", label="CENTCOM", kind="organization"),
            dict(id="rejtf", label="Rapid Employment Joint Task Force", kind="program"),
            dict(id="navcent", label="NAVCENT / Fifth Fleet", kind="organization"),
            dict(id="apfit", label="APFIT", kind="program"),
            dict(id="research-engineering", label="Research & Engineering", kind="organization"),
        ],
        edges=[
            relationship("lucas-network-industrial", "spektreworks", "lucas", "industrial", "Attributed manufacturer", "Reuters attributes whole-aircraft manufacture to SpektreWorks. The edge does not identify subcontractors or production premises.", "attributed", "2026-03-04", ("lucas-reuters-production", "Manufacturer and manufacturing-contract attribution."), entity_id="spektreworks"),
            relationship("lucas-network-sponsor", "marine-corps", "lucas", "program", "Evaluation sponsor", "The Army identifies Marine Corps sponsorship of the evaluated aircraft, without assigning manufacturing workshare.", "attributed", "2025-12-03", ("lucas-yuma-evaluation", "Opening program description.")),
            relationship("lucas-network-test", "yuma-evaluation", "lucas", "evaluation", "Hosted evaluation", "Yuma's documented role is evaluation; it is not presented as a supplier factory.", "attributed", "2025-12-03", ("lucas-yuma-evaluation", "Evaluation venue.")),
            relationship("lucas-network-command", "soccent", "scorpion-strike", "program", "Led task-force effort", "CENTCOM identifies SOCCENT personnel as leading Scorpion Strike's squadron-building effort.", "attributed", "2025-12-03", ("lucas-centcom-squadron", "Final paragraph: SOCCENT role.")),
            relationship("lucas-network-fielding", "scorpion-strike", "lucas", "program", "Fielded squadron", "CENTCOM identifies LUCAS aircraft with Scorpion Strike's announced squadron. Fielding is not manufacture.", "attributed", "2025-12-03", ("lucas-centcom-squadron", "Squadron aircraft identification.")),
            relationship("lucas-network-naval", "task-force-59", "lucas", "evaluation", "Conducted naval demonstration", "The Navy identifies Task Force 59 as the demonstration operator, without assigning industrial supply responsibility.", "attributed", "2025-12-16", ("lucas-navy-sea", "Task Force 59 demonstration role.")),
            relationship("lucas-network-developer", "spektreworks", "lucas", "industrial", "Attributed developer", "National Defense explicitly identifies SpektreWorks as LUCAS developer. This documents a second industrial role, not another supplier.", "attributed", "2025-08-15", ("lucas-pentagon-showcase", "Firsthand showcase report: LUCAS developer attribution."), entity_id="spektreworks"),
            relationship("lucas-network-funding", "apfit", "lucas", "program", "FY2025 project funding", "APFIT lists $30 million for the Marine Corps LUCAS project. No company payment or manufacturing allocation is established.", "attributed", "2025-06-17", ("lucas-apfit-funding", "FY2025 project list: LUCAS allocation and Marine Corps association.")),
            relationship("lucas-network-apfit-office", "research-engineering", "apfit", "program", "Administers funding program", "The June release identifies APFIT as a Research & Engineering program supporting production transition.", "attributed", "2025-06-17", ("lucas-apfit-funding", "Opening paragraphs: office's APFIT program and transition into production.")),
            relationship("lucas-network-rejtf-established", "centcom", "rejtf", "program", "Established innovation task force", "CENTCOM announced REJTF's establishment on September 23, led by its chief technology officer.", "attributed", "2025-09-23", ("lucas-rejtf-establishment", "Opening paragraphs: establishment and organizational leadership.")),
            relationship("lucas-network-rejtf-alignment", "scorpion-strike", "rejtf", "program", "Aligns with capability focus", "Scorpion Strike's squadron effort aligns with REJTF's capability work. Alignment does not establish a subordinate command relationship.", "attributed", "2025-12-03", ("lucas-centcom-squadron", "Final paragraph: explicitly stated REJTF capability-focus alignment.")),
            relationship("lucas-network-scorpion-established", "centcom", "scorpion-strike", "program", "Established task force", "CENTCOM announced the creation of Scorpion Strike, which had established a LUCAS squadron.", "attributed", "2025-12-03", ("lucas-centcom-squadron", "Opening task-force announcement and squadron identification.")),
            relationship("lucas-network-soccent-component", "centcom", "soccent", "program", "Special-operations component", "CENTCOM's official directory lists SOCCENT among its component commands. This reviewed relationship has no inferred founding date.", "context", "Directory reviewed 2026-09-10", ("lucas-centcom-components", "Component Commands introduction and SOCCENT listing.")),
            relationship("lucas-network-maritime-component", "centcom", "navcent", "program", "Maritime component", "The Navy identifies NAVCENT/Fifth Fleet as CENTCOM's maritime component.", "attributed", "2025-12-18", ("lucas-navy-sea", "Closing NAVCENT/C5F organizational description.")),
            relationship("lucas-network-tf59-established", "navcent", "task-force-59", "program", "Established unmanned-systems task force", "NAVCENT established Task Force 59 in September 2021. This institutional origin predates its documented LUCAS demonstration.", "attributed", "2021-09-09", ("lucas-tf59-establishment", "Opening announcement and TF59 commissioning caption.")),
        ],
    ),
)

DOSSIERS = [LUCAS]
